SportsStore/Controllers/AdminController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Controllers
{
    [Authorize]
    public class AdminController:Controller
    {
        private IProductRepository _repository;

        public AdminController(IProductRepository repository) => _repository = repository;

        public ViewResult Index() => View(_repository.Products);

        public ViewResult Edit(int productId) =>
            View(_repository.Products
                .FirstOrDefault(p => p.ProductId == productId));

        [HttpPost]
        public IActionResult Edit(Product product)
        {
            if (ModelState.IsValid)
            {
                _repository.SaveProduct(product);
                TempData["message"] = $"{product.Name} has been saved!";
                return RedirectToAction("Index");
            }
            else
            {
                // Something wrong with the data values
                return View(product);
            }
        }

        public IActionResult Create() => View("Edit", new Product());

        [HttpPost]
        public IActionResult Delete(int productId)
        {
            Product deletedProduct = _repository.DeleteProduct(productId);
            if (deletedProduct != null)
                TempData["message"] = $"{deletedProduct.Name} was deleted!";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult SeedDatabase()
        {
            SeedData.EnsurePopulated(HttpContext.RequestServices);
            return RedirectToAction(nameof(Index));
        }
    }
}

SportsStore/Controllers/CartController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository _repository;
        private Cart cart;

        public CartController(IProductRepository repo, Cart cartService)
        {
            _repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int productId, string returnUrl)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
                cart.AddItem(product, 1);

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int productId, string returnUrl)
        {
            Product product = _repository.Products
                .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
                cart.RemoveLine(product);

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        
        [Authorize]
        public ViewResult List() =>
            View(repository.Orders.Where(o => !o.Shipped));

        [HttpPost]
        [Authorize]
        public IActionResult MarkShipped(int orderID)
        {
            Order order = repository.Orders
                .FirstOrDefault(o => o.OrderID == orderID);
            if (order != null)
            {
                order.Shipped = true;
                repository.SaveOrder(order);
            }

            return RedirectToAction(nameof(List));
        }

        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (!cart.Lines.Any())
                ModelState.AddModelError("", "Sorry, your cart is empty!");

            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                return RedirectToAction(nameof(Completed));
            }
            else
                return View(order);
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

SportsStore/Controllers/ProductController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;
using SportsStore.Models.ViewModels;

namespace SportsStore.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repository;
        public int PageSize = 12;

        public ProductController(IProductRepository repository) => _repository = repository;

        public ViewResult List(string category, int productPage = 1)
            => View(new ProductsListViewModel
            {
                Products = _repository.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((productPage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null
                        ? _repository.Products.Count()
                        : _repository.Products.Count(e => e.Category == category)
                },
                CurrentCategory = category
            });
    }
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card card-outline-primary" style="display: flex; flex-direction: column; justify-content: space-between; width: 18rem; margin: 10px;">
    <img class="card-img-top" src="@Model.ImageUrl" alt="Card image cap">
    <div class="card-body" style="padding: 20px">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.Description</p>
        <div style="display: flex; justify-content: space-between">
            <div class="badge badge-pill badge-primary" style="display: flex; justify-content: center; align-items: center">
                <span>@Model.Price.ToString("0.00")$</span>
            </div>
            <form id="@Model.ProductId" asp-action="AddToCart"
                      asp-controller="Cart" method="post">
                <input type="hidden" asp-for="ProductId"/>
                <input type="hidden" name="returnUrl"
                       value="@ViewContext.HttpContext.Request.PathAndQuery()"/>
                <span class="card-text p-1">
                    <button type="submit"
                            class="btn btn-success btn-sm pull-right"
                            style="float: right; cursor: pointer">
                        Add to Cart
                    </button>
                </span>
            </form>
        </div>
    </div>
</div>

SportsStore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="~/images/icon.png" type="image/png"/>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/_AdminLayout.css"/>
</head>
<body>
    <header class="row">
        <div class="col">
            <h4>@ViewBag.Title</h4>
        </div>
        <div class="col-2">
            <a class="btn btn-outline-secondary" asp-action="Logout"
               asp-controller="Account">Log Out</a>
            <a class="btn btn-outline-secondary"
               asp-action="List" asp-controller="Product">Home page</a>
        </div>
    </header>
    <div class="wrap">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>

    <script src="~/lib/tether/dist/js/tether.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" href="~/images/icon.png" type="image/png"/>
    <title>SportsStore</title>
    <meta name="viewport" content="width=device-width"/>
    <link rel="stylesheet" type="text/css" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    <link rel="stylesheet" type="text/css" href="~/lib/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" type="text/css" href="~/css/_Layout.css"/>
</head>
<body>
    <div class="wrap">
        <header class="navbar bg-inverse">
                <div class="row">
                    <a class="col navbar-inverse navbar-brand" href="/">
                        <img src="~/images/logo.png" alt="Logo" class="logo"/>SPORTS STORE
                    </a>
                    <div class="col-4 text-right" style="display: flex; justify-content: flex-end; align-items: center;">
                        @await Component.InvokeAsync("CartSummary")
                    </div>
                </div>
            </header>
            <section class="section">
                <nav id="categories" class="navbar bg-inverse">
                    @await Component.InvokeAsync("NavigationMenu")
                </nav>
                <main class="products">
                    @RenderBody()
                    <footer class="footer navbar bg-inverse">
                            <div class="footer-text">
                                <p>©&nbsp;Internet-shop «Sports Store™»</p>
                                <p>Training project 2021 - @DateTime.Now.Year</p>
                            </div>
                            <div class="footer-img">
                                <img src="~/images/mastercard-logo.svg" alt="Mastercard"/>
                                <img src="~/images/visa-logo.svg" alt="Visa"/>
                            </div>
                            <div>
                                <a class="btn btn-outline-secondary"
                                   asp-action="Index"
                                   asp-controller="Admin"
                                >Admin page</a>
                                <a class="btn btn-outline-secondary"
                                   asp-action="List" asp-controller="Order">Orders</a>
                            </div>
                        </footer>
                </main>
            </section>
    </div>
    
    <script src="~/lib/tether/dist/js/tether.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
</body>
</html>